### PR TITLE
append

### PR DESCRIPTION
**Pull request by ArmandDj**

### CODE REVIEW

**Comment by hannakohxt** [comment]
You have duplicate code. That's also why it wasn't working. You have double of all the functions in the views.py file

**Comment by ArmandDj** [comment]
shit haha i see it now

**Comment by ArmandDj** [comment]
alright hopefully that'll fix it, sorry about that

**Comment by hannakohxt** [comment]
Thanks! Could you pull Andy's most recent changes and rebase?

**Comment by ArmandDj** [comment]
i thought i did?

**Pull request merged**
